# Include guard for the Makefile
ifndef DRIVER_MAKEFILE_
DRIVER_MAKEFILE_=included

# Get the user defined variables, if they specified them
-include config.mk
# Export user variables for the Kbuild file and kernel Makefile
ifdef CROSS_COMPILE
    export CROSS_COMPILE
endif
ifdef ARCH
    export ARCH
endif

# The kernel symbols file, used to determine if the kernel has been updated
KERNEL_SYMS = $(KBUILD_DIR)/Module.symvers

# The list of source files for the driver. Export the names to the Kbuild file.
DRIVER_DIR = driver
export AXIDMA_FILES = tempt.c paremeter.h covid2.h conv2d.h max_pooling.h utility.h

#DRIVER_PATHS = driver/tempt.c
DRIVER_PATHS = $(addprefix $(DRIVER_DIR)/,$(AXIDMA_FILES))

# The kernel object files generated by compilation
export AXIDMA_MODULE_NAME = driver
DRIVER_OBJECT = $(DRIVER_DIR)/$(AXIDMA_MODULE_NAME).ko

#Should be outputs/tempt.ko
DRIVER_OUTPUT_OBJECT = $(OUTPUT_DIR)/$(AXIDMA_MODULE_NAME).ko

# Export the include directories to the Kbuild file, making sure the path is
# absolute, as the kernel Makefile is run in a different directory.
#export AXIDMA_INC_DIRS = $(PWD)/$(LIBAXIDMA_INC_DIRS)

################################################################################
# Targets
################################################################################

# These targets don't correspond to actual generated files
.PHONY: driver driver_clean kbuild_def_check arch_def_check \
		kbuild_exists_check kbuild_built_check

# User-facing targets for compiling the driver
driver: $(DRIVER_OUTPUT_OBJECT)

# Compile the driver against the given kernel. The check targets are phony, so
# don't force this target to run because of them.
$(DRIVER_OBJECT): $(DRIVER_PATHS) $(KERNEL_SYMS) 
	make -C $(KBUILD_DIR) M=$(PWD)/$(DRIVER_DIR) modules

# Copy the compiled driver to the specified output directory
$(DRIVER_OUTPUT_OBJECT): $(DRIVER_OBJECT) $(OUTPUT_DIR)
	@cp $< $@

#  
# Clean up all the files generated by compiling the driver
driver_clean:
	rm -f $(DRIVER_OUTPUT_OBJECT)
	make -C $(KBUILD_DIR) M=$(PWD)/$(DRIVER_DIR) clean
	
endif # DRIVER_MAKEFILE_
